const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const ts = require('typescript')
const vm = require('node:vm')
const context = { exports: {} }
vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/utils/diffDocument.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText, context)
const { indexDiff, getDiffRows, lineAtOffset, findDiffMatch } = context.exports

test('full-document statistics exclude headers and preserve blank and CRLF lines', () => {
  const text = '--- old\r\n+++ new\r\n@@ -1 +1 @@\r\n-old\r\n+new\r\n context\r\n\r\n'
  const index = indexDiff(text)
  assert.equal(index.added, 1)
  assert.equal(index.removed, 1)
  const rows = getDiffRows(text, index, 0, index.offsets.length)
  assert.equal(rows.length, 8)
  assert.equal(rows[0].className, 'diff-meta')
  assert.equal(rows[3].text, 'old')
  assert.equal(rows[3].marker, '-')
  assert.equal(rows[4].text, 'new')
  assert.equal(rows[5].text, ' context')
  assert.equal(rows[7].text, '')
  assert.equal(lineAtOffset(index, text.indexOf('+new') + 1), 4)
  assert.equal(indexDiff('').offsets.length, 0)
})
test('only requested rows are materialized while statistics cover offscreen lines', () => {
  const text = Array.from({ length: 100000 }, (_, i) => `${i % 2 ? '+' : '-'}line-${i}`).join('\n')
  const index = indexDiff(text)
  assert.equal(index.offsets.length, 100000)
  assert.equal(index.added, 50000)
  assert.equal(index.removed, 50000)
  const rows = getDiffRows(text, index, 99980, 100000)
  assert.equal(rows.length, 20)
  assert.equal(rows[0].index, 99981)
  assert.equal(rows.at(-1).text, 'line-99999')
  assert.equal(lineAtOffset(index, text.length - 1), 99999)
})
test('offscreen wide lines, tabs, and Unicode contribute to horizontal width', () => {
  const index = indexDiff('+short\n+' + 'x'.repeat(1000) + '\n+\t漢字')
  assert.equal(index.maxColumns, 1000)
  assert.equal(indexDiff('+\t漢字').maxColumns, 12)
})
test('full-text search finds offscreen matches, cycles in both directions, and handles missing matches', () => {
  const text = '+needle\n-context\n+needle'
  assert.equal(findDiffMatch(text, 'needle', 0, 'next'), 1)
  const last = findDiffMatch(text, 'needle', 2, 'next')
  assert.equal(last, text.lastIndexOf('needle'))
  assert.equal(findDiffMatch(text, 'needle', last + 1, 'next'), 1)
  assert.equal(findDiffMatch(text, 'needle', 0, 'previous'), last)
  assert.equal(findDiffMatch(text, 'needle', last - 1, 'previous'), 1)
  assert.equal(findDiffMatch(text, 'NEEDLE', 0, 'next'), -1)
  assert.equal(findDiffMatch(text, '', 0, 'next'), -1)
})
